"""Inference engine module for communicating with the local Ollama daemon."""

from collections.abc import Generator
from contextlib import contextmanager
from typing import Any

import httpx
import ollama


class OllamaEngineError(Exception):
    """Base exception for all failures originating within inference engine"""

class OllamaConnectionError(OllamaEngineError):
    """Base exception for network connection issues with Ollama"""

class ModelNotFoundError(OllamaEngineError):
    """Raised when specified model not in local registry"""

class InferenceEngine:
    """manages connections with Ollama and token streaming"""

    def __init__(
        self,
        model: str = "qwen2.5:7b-instruct",
        host: str = "http://localhost:11434",
        timeout: float = 60.0,
    ):
        self.model = model
        self.host = host.rstrip("/")
        self.ollama_client = ollama.Client(host=host, timeout=timeout)

    @contextmanager
    def _error_boundary(
        self, action: str = "inference"
    ) -> Generator[None, None, None]:
        """Centralized error boundary translating low-level network/Ollama errors."""
        try:
            yield
        except (httpx.ConnectError, httpx.ConnectTimeout) as exc:
            raise OllamaConnectionError(
                f"Could not connect to Ollama daemon at '{self.host}' during"
                f" {action}. Ensure 'ollama serve' is running."
            ) from exc
        except ollama.ResponseError as exc:
            if exc.status_code == 404:
                raise ModelNotFoundError(
                    f"Model '{self.model}' not found by Ollama."
                ) from exc
            raise OllamaEngineError(
                f"Ollama server error [{exc.status_code}] during {action}:"
                f" {exc.error}"
            ) from exc
        except OllamaEngineError:
            # Let our own domain exceptions pass through without double-wrapping
            raise
        except Exception as exc:
            raise OllamaEngineError(
                f"Unexpected error during {action}: {exc}"
            ) from exc

    def verify_ready(self) -> None:
        with self._error_boundary("readiness check"):
            response = self.ollama_client.list()

            models = response.get("models", [])
            model_names: list[str] = []
            for model in models:
                model_name = model.get("model") or model.get("name") or ""
                if model_name:
                    model_names.append(model_name)

            for model_name in model_names:
                if (
                    model_name == self.model
                    or model_name == f"{self.model}:latest"
                    or self.model == f"{model_name}:latest"
                ):
                    #found match, return early to avoid throwing error
                    return
                
            raise ModelNotFoundError(
                f"Model '{self.model}' is not available locally. "
                f"Run 'ollama pull {self.model}' in your terminal to download it."
            )

    def stream_chat(
        self,
        messages: list[dict[str, Any]],
        options: dict[str, Any] | None = None,
    ) -> Generator[str, None, None]:
        """Streams text tokens generated by model for ongoing conversation."""

        with self._error_boundary("token streaming"):
            response = self.ollama_client.chat(
                model=self.model,
                messages=messages,
                stream=True,
                options=options or {}
            )

            for chunk in response:
                content = chunk.get("message", {}).get("content", "")
                if content:
                    yield content
